import { build } from "esbuild";

const result = await build({
  entryPoints: ["server/index.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  outfile: "dist/index.js",
  external: [
    // Node.js built-ins
    "fs",
    "path",
    "crypto",
    "http",
    "https",
    "url",
    "querystring",
    "os",
    "child_process",
    "cluster",
    "dgram",
    "dns",
    "net",
    "readline",
    "repl",
    "stream",
    "string_decoder",
    "tls",
    "tty",
    "util",
    "v8",
    "vm",
    "worker_threads",
    "zlib",
    "events",
    "assert",
    "buffer",
    "constants",
    "domain",
    "punycode",
    "timers",
    "tty",
    "querystring",

    // All npm packages should be external
    "express",
    "cors",
    "helmet",
    "morgan",
    "dotenv",
    "bcryptjs",
    "jsonwebtoken",
    "passport",
    "express-session",
    "express-rate-limit",
    "express-slow-down",
    "express-validator",
    "express-mongo-sanitize",
    "hpp",
    "memorystore",
    "connect-pg-simple",
    "ws",
    "pg",
    "drizzle-orm",
    "drizzle-orm/pg-core",
    "drizzle-zod",
    "zod",
    "@neondatabase/serverless",
    "stripe",
    "axios",
    "uuid",
    "date-fns",
    "i18n-iso-countries",
    "sitemap",

    // React and frontend dependencies
    "react",
    "react-dom",
    "@radix-ui/*",
    "framer-motion",
    "lucide-react",
    "react-hook-form",
    "@hookform/resolvers",
    "react-icons",
    "react-leaflet",
    "leaflet",
    "@vis.gl/react-google-maps",
    "@tanstack/react-query",
    "react-day-picker",
    "react-helmet-async",
    "react-resizable-panels",
    "react-swipeable",
    "react-zoom-pan-pinch",
    "recharts",
    "embla-carousel-react",
    "wouter",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "tailwindcss-animate",
    "cmdk",
    "vaul",
    "input-otp",
    "@stripe/react-stripe-js",
    "@stripe/stripe-js",
    "recharts",
    "sitemap",

    // Build tools
    "vite",
    "@vitejs/plugin-react",
    "autoprefixer",
    "postcss",
    "tailwindcss",
    "typescript",
    "ts-node",
    "tsx",
    "esbuild",
    "concurrently",
    "cross-env",
    "drizzle-kit",
    "@replit/*",
    "@tailwindcss/typography",

    // Dev dependencies
    "@types/*",
    "bufferutil",
  ],
  sourcemap: false,
  minify: true,
  treeShaking: true,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  loader: {
    ".ts": "ts",
    ".js": "js",
  },
});

if (result.errors.length > 0) {
  console.error("Build errors:", result.errors);
  process.exit(1);
}

console.log("Server build completed successfully!");
